#!/bin/sh

mkdir lib
touch lib/environment.js         # <- general configuration
touch lib/methods.js             # <- Meteor.method definitions
touch lib/external.js               # <- common code from someone else

mkdir collections 				 # <- definitions of collections and methods on them (could be models/)

mkdir client
mkdir client/lib
mkdir client/views
mkdir client/stylesheets

touch client/lib                 # <- client specific libraries (also loaded first)
touch client/lib/environment.js  # <- configuration of any client side packages
touch client/lib/helpers         # <- any helpers (handlebars or otherwise) that are used often in view files
touch client/application.js      # <- subscriptions, basic Meteor.startup code.
touch client/index.html          # <- toplevel html
touch client/index.js            # <- and its JS
touch client/views/myPage.html   # <- the templates specific to a single page
touch client/views/myPage.js     # <- and the JS to hook it up
touch client/views/types/       # <- if you find you have a lot of views of the same object type
touch client/stylesheets/        # <- css / styl / less files

mkdir server/lib
touch server/publications.js     # <- Meteor.publish definitions
touch server/lib/environment.js  # <- configuration of server side packages

mkdir public/                    # <- static files, such as images, that are served directly.

mkdir tests/                     # <- unit test files (won't be loaded on client or server)
